# NumPy Arrays

In this notebook, I will be exploring three main methods to create NumPy arrays
1. Transforming standard python list
2. Built-in functions
3. Generating random data

I will also discuss some key attributes of NumPy arrays

In [1]:
import numpy as np

## Transforming Standard Python List

In [2]:
mylist = [1, 2, 3]
mylist

[1, 2, 3]

In [3]:
type(mylist)

list

In [4]:
np.array(mylist)

array([1, 2, 3])

In [5]:
mylist

[1, 2, 3]

In [6]:
type(mylist)

list

In [7]:
myarr = np.array(mylist)
myarr

array([1, 2, 3])

In [8]:
type(myarr)

numpy.ndarray

### 2D Vectors

In [9]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Functions

### arange

In [11]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

### Zeros

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### Ones

In [15]:
np.ones(4)

array([1., 1., 1., 1.])

In [16]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

### Linspace

In [17]:
np.linspace(start=0, stop=10, num=3)

array([ 0.,  5., 10.])

In [18]:
np.linspace(start=0, stop=10, num=11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

### Eye -> used to creating identity matrix

In [19]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Generating Random Data

### Uniform Distribution

In [20]:
np.random.rand(1)

array([0.9768237])

In [21]:
np.random.rand(5,3)

array([[0.87549956, 0.80039464, 0.55303089],
       [0.3105037 , 0.64429443, 0.46953395],
       [0.35143707, 0.02644795, 0.39915289],
       [0.46977535, 0.16852078, 0.40418809],
       [0.19581188, 0.05485209, 0.39980685]])

### Normal Distribution

In [22]:
np.random.randn(1)

array([1.07635795])

In [23]:
np.random.randn(5,3)

array([[-0.47785138,  1.13787917,  0.69975992],
       [-0.76741641, -0.7471411 , -0.09900801],
       [-0.12333392, -0.9620552 ,  1.00814582],
       [ 0.68811743, -1.3087681 , -0.48827044],
       [ 1.3597012 ,  0.73898669, -0.66768337]])

### Random Integer

In [24]:
np.random.randint(0, 101)

6

In [25]:
np.random.randint(0, 101, 10)

array([71, 24, 37, 48, 20, 12, 12, 50, 93, 58])

In [26]:
np.random.randint(0, 101, (4,5))

array([[65, 28, 15,  7, 61],
       [88, 58,  5, 85, 21],
       [19, 19, 58, 50,  5],
       [ 9, 57, 90, 31, 95]])

### Using Seed

In [27]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

## Other Common Attributes

### Reshape Method

In [28]:
arr = np.arange(0, 25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [29]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [30]:
arr.reshape(5,4)

ValueError: cannot reshape array of size 25 into shape (5,4)

### Max, Min, Argmax and Argmin

In [31]:
random_array = np.random.randint(0, 101, 10)
random_array

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [32]:
random_array.max()

99

In [33]:
random_array.min()

2

In [34]:
random_array.argmax()

5

In [35]:
random_array.argmin()

7

### Data Type

In [36]:
random_array = np.random.randint(0, 101, 10)
random_array

array([ 1, 87, 29, 37,  1, 63, 59, 20, 32, 75])

In [37]:
random_array.dtype

dtype('int64')

### Shape as an attribute, not a method call

In [38]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [39]:
arr.shape

(25,)

In [40]:
arr = arr.reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [41]:
arr.shape

(5, 5)

# THE END