# Indexing and Selection

1. Grabbing single element
2. Grabbing a slice of element
3. Broadcasting selections
4. Indexing and selections in 2-dimensionals
5. Conditional selections

In [1]:
import numpy as np

In [2]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Grabbing a Single Element

In [3]:
arr[4]

4

In [4]:
arr[9]

9

## Grabbing a Slice of Elements

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[1:4]

array([1, 2, 3])

In [7]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [8]:
arr[:5]

array([0, 1, 2, 3, 4])

In [9]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [10]:
arr[5:11]

array([ 5,  6,  7,  8,  9, 10])

## Broadcasting

In [11]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
arr[:5] = 100

In [13]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [14]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
slice_of_array = arr[0:5]
slice_of_array

array([0, 1, 2, 3, 4])

In [16]:
slice_of_array[:] = 99

In [17]:
slice_of_array

array([99, 99, 99, 99, 99])

Original array will be effected

In [18]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

If we do not want original array to be effected

In [19]:
arr_copy = arr.copy()

In [20]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [21]:
arr_copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [22]:
arr_copy[:] = 100

In [23]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [24]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

## Indexing and selections in 2-dimensionals

In [25]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [26]:
arr_2d.shape

(3, 3)

### Grabbing 1st row

In [27]:
arr_2d[0]

array([ 5, 10, 15])

### Grabbing single element

In [28]:
arr_2d[1,1]

25

### Slicing

In [29]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

## Conditional Selection

In [30]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [32]:
bool_arr = arr > 4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [33]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

### Doing above steps in single line

In [34]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

# THE END