# NumPy Operations

In [1]:
import numpy as np

In [2]:
arr = np.arange(0, 10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Adding a Scalar Number

In [3]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Subtracting a Scalar Number

In [4]:
arr - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

## Adding an array with an array
**must be of same size**

In [5]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## Multiply an array with an array
**must be of same size**

In [6]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

## Subtracting an array with an array
**must be of same size**

In [7]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Dividing an array with array
**must be of same size**

In [8]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr / arr

/tmp/ipykernel_4882/3001117470.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

## Other Mathematical Functions

### Square root

In [10]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

### Trignometric functions

In [11]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [12]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [13]:
np.tanh(arr)

array([0.        , 0.76159416, 0.96402758, 0.99505475, 0.9993293 ,
       0.9999092 , 0.99998771, 0.99999834, 0.99999977, 0.99999997])

In [14]:
np.log(arr)

/tmp/ipykernel_4882/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

### Other Mathematical Functions

In [15]:
arr.mean()

4.5

In [16]:
arr.sum()

45

In [17]:
arr.max()

9

In [18]:
arr.min()

0

In [19]:
arr.var()

8.25

In [20]:
arr.std()

2.8722813232690143

## 2-D Arrays

In [21]:
arr_2d = np.arange(0,25).reshape(5,5)
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [22]:
arr_2d.sum()

300

### Sum across the rows

This will perform operation across the rows, which gives sum of columns

In [23]:
arr_2d.sum(axis=0)

array([50, 55, 60, 65, 70])

### Sum across the columns

This will perform operation across the rows, which gives sum of rows

In [24]:
arr_2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])